name: thelist-ca-tests-dev
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:
jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: dev-ca thelist-710labs.com
      EXECUTION_TYPE: Scheduled Daily Run
      RUN_ID: ${{ env.GITHUB_RUN_NUMBER }}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_DEV }}
      RESULTS_URL: 'https://710labs.github.io/seventen-functional-tests/'
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      DEFAULT_VIDEO_PREVIEW_URL: https://tymber-s3.imgix.net/herbnjoy-beverly-hills-350/product-brand-63616/d17157b5-8a90-48b1-aeb6-d0e092351548.png?s=480dd20057b2bd21b3b6d6200a3c0679
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to CA
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=ca
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:dev:ca
      - name: Upload Playwright Test Results History to S3
        uses: PavanMudigonda/playwright-html-reporter-s3-website@v1.1
        id: aws_s3_test_results_upload
        with:
          report_url: http://${{ secrets.S3_BUCKET }}.s3-website-${{ env.s3_REGION }}.amazonaws.com
          test_results: test-results
          results_history: results-history
          keep_reports: 20
          args: --acl public-read --follow-symlinks. 
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
          AWS_REGION: ${{ secrets.S3_REGION}}
          SOURCE_DIR: 'results-history'
          DEST_DIR: ${{ env.GITHUB_RUN_NUMBER }}
