name: thelist-fl-smoke-tests-prod
on: workflow_dispatch
jobs:
  smoke-test-prod-fl:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_PROD_FL }}
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run smoke:test:prod:fl
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/73088225
          SLACK_MESSAGE: env-prod-fl-smoke-test(https://thelist.710labs.com) status-${{ job.status }} Report Url-${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: Test Run Status thelist-ca-smoke
          SLACK_USERNAME: "710 Functional Tests"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
