name: thelist-pos-order-generator
on:
  workflow_dispatch:
    inputs:
        order_count:
          description: 'Number of Orders to Create'     
          required: true
          default: '1'
jobs:
  pos-order-gerenator:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_DEV }}
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run helper:acuityslots
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/73088225
          SLACK_MESSAGE: Executed Acuity Slot Helper in Dev. Status-${{ job.status }} Report Url-${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: Task Run Status thelist-ca-acuity-slot-helper
          SLACK_USERNAME: "710 Functional Tests"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          ORDER_COUNT: ${{ github.event.inputs.order_count }}
