name: thelist-acuity-slot-helper-dev
on:
  schedule:
    - cron: "0 6 * * 1,3,5"
  workflow_dispatch:
jobs:
  acuity-slot-helper:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_DEV }}
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      ACUITY_USER: ${{ secrets.ACUITY_USER }}
      ACUITY_PASSWORD: ${{ secrets.ACUITY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run helper:acuityslots:dev
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/73088225
          SLACK_MESSAGE: Executed Acuity Slot Helper in Dev. Status-${{ job.status }} Report Url-${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: Task Run Status thelist-ca-acuity-slot-helper
          SLACK_USERNAME: "710 Functional Tests"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
