name: thelist-ca-tests-stage
on:
  workflow_dispatch:
jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: stage-ca thelist-stage.710labs.com
      EXECUTION_TYPE: Build Validation
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_STAGE }}
      RESULTS_URL: "https://710labs.github.io/seventen-functional-tests/"
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to CA
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_STAGE }}${{ secrets.QA_ENDPOINT }}domains/update/?state=ca
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:staging:ca
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
