name: thelist-ca-pos-order-generator
on:
  workflow_dispatch:
    inputs:
      order_count:
        description: "Order Count"
        required: true
        default: "1"
      prefix:
        description: "Unique Prefix"
        required: false
        default: ""
      address:
        description: "Address"
        required: false
        default: "3324 S La Cienega Blvd, Los Angeles"
      fulfillment_type:
        type: choice
        description: Fulfillment Type
        options:
          - Random
          - Pickup
          - Delivery
      customer_type:
        type: choice
        description: Customer Type
        options:
          - Random
          - Medical
          - Recreational
      cart_type:
        type: choice
        description: Cart Type
        options:
          - Random
      environment:
        type: choice
        description: Fulfillment Type
        options:
          - dev
          - stage
          - prod
jobs:
  pos-order-generator:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV_ID: pos-sync-ca-${{ github.event.inputs.environment }}
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_DEV }}
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      POSSYNC_ORDER_COUNT: ${{ github.event.inputs.order_count }}
      POSSYNC_PREFIX: ${{ github.event.inputs.prefix }}
      POSSYNC_ADDRESS: ${{ github.event.inputs.address }}
      POSSYNC_FULFILLMENT_TYPE: ${{ github.event.inputs.fulfillment_type }}
      POSSYNC_CUSTOMER_TYPE: ${{ github.event.inputs.customer_type }}
      POSSYNC_CART_TYPE: ${{ github.event.inputs.cart_type }}
      POSSYNC_ENVIRONMENT: ${{ github.event.inputs.environment }}
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
    steps:
      - name: Set environment variable based on condition
        run: |
          if [ ${{ github.event.inputs.environment }} == "stage" ]; then
            echo "Setting stage url"
            echo "POSSYNC_URL=${{ secrets.BASE_URL_STAGE }}" >> $GITHUB_ENV
          elif [ ${{ github.event.inputs.environment }} == "dev" ]; then
            echo "Setting stage url"
            echo "POSSYNC_URL=${{ secrets.BASE_URL_DEV }}" >> $GITHUB_ENV
          else
            echo "Setting MY_ENV_VARIABLE=development"
            echo "MY_ENV_VARIABLE=development" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to CA
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ env.POSSYNC_URL }}${{ secrets.QA_ENDPOINT }}domains/update/?state=ca
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
          node-version: '16.x'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run helper:possync_orders
